/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.emp.gl.time.control;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.emp.gl.changeetatinterface.changeOrientation;
import org.emp.gl.core.lookup.Lookup;
import org.emp.gl.time.action.TimeActionInterface;

/**
 *
 * @author ahmed
 */
public class GuiControl extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form GuiControl
     */
    public GuiControl() {
        initComponents();

        this.downButtom.addActionListener(this);
        this.rightButtom.addActionListener(this);
        this.upButtom.addActionListener(this);
        this.leftButtom.addActionListener(this);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upButtom = new javax.swing.JButton();
        rightButtom = new javax.swing.JButton();
        comment = new javax.swing.JLabel();
        downButtom = new javax.swing.JButton();
        leftButtom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Setting Smart Watch");

        upButtom.setFont(new java.awt.Font("Algerian", 0, 25)); // NOI18N
        upButtom.setText("UP");
        upButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtomActionPerformed(evt);
            }
        });

        rightButtom.setFont(new java.awt.Font("Algerian", 0, 25)); // NOI18N
        rightButtom.setText("Right");
        rightButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightButtomActionPerformed(evt);
            }
        });

        comment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        downButtom.setFont(new java.awt.Font("Algerian", 0, 25)); // NOI18N
        downButtom.setText("down");
        downButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButtomActionPerformed(evt);
            }
        });

        leftButtom.setFont(new java.awt.Font("Algerian", 0, 25)); // NOI18N
        leftButtom.setText("Left");
        leftButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(leftButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(downButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rightButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(upButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(upButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(comment, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rightButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightButtomActionPerformed
        // TODO add your handling code here:
        ((changeOrientation) Lookup.getInstance().getService(changeOrientation.class)).tournerDroite();

    }//GEN-LAST:event_rightButtomActionPerformed

    private void upButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtomActionPerformed
        // TODO add your handling code here:
        ((changeOrientation) Lookup.getInstance().getService(changeOrientation.class)).tournerHaut();

    }//GEN-LAST:event_upButtomActionPerformed

    private void downButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButtomActionPerformed
        // TODO add your handling code here:
        ((changeOrientation) Lookup.getInstance().getService(changeOrientation.class)).tournerBas();
    }//GEN-LAST:event_downButtomActionPerformed

    private void leftButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftButtomActionPerformed
        // TODO add your handling code here:
        ((changeOrientation) Lookup.getInstance().getService(changeOrientation.class)).tournerGauche();
    }//GEN-LAST:event_leftButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel comment;
    private javax.swing.JButton downButtom;
    private javax.swing.JButton leftButtom;
    private javax.swing.JButton rightButtom;
    private javax.swing.JButton upButtom;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == this.leftButtom) {
            ((changeOrientation) Lookup.getInstance().getService(changeOrientation.class)).tournerGauche();
            return;
        }

        if (e.getSource() == this.rightButtom) {
            ((changeOrientation) Lookup.getInstance().getService(changeOrientation.class)).tournerDroite();
            return;
        }
        if (e.getSource() == this.upButtom) {
            ((changeOrientation) Lookup.getInstance().getService(changeOrientation.class)).tournerHaut();
            return;
        }
        if (e.getSource() == this.downButtom) {
            ((changeOrientation) Lookup.getInstance().getService(changeOrientation.class)).tournerBas();
        }
    }
}
